DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS role_users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;