// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Category struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	UpSelling sql.NullString `json:"up_selling"`
	Parent    int64          `json:"parent"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	CreatedBy sql.NullInt64  `json:"created_by"`
	UpdatedBy sql.NullInt64  `json:"updated_by"`
	DeletedBy sql.NullInt64  `json:"deleted_by"`
}

type Madiastorage struct {
	ID        int64         `json:"id"`
	SecID     string        `json:"sec_id"`
	TabID     string        `json:"tab_id"`
	Name      string        `json:"name"`
	Type      string        `json:"type"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	DeletedBy sql.NullInt64 `json:"deleted_by"`
}

type Partner struct {
	ID          int64         `json:"id"`
	Name        string        `json:"name"`
	User        string        `json:"user"`
	Secret      string        `json:"secret"`
	AddInfo1    string        `json:"add_info1"`
	AddInfo2    string        `json:"add_info2"`
	ValidFrom   sql.NullTime  `json:"valid_from"`
	ValidTo     sql.NullTime  `json:"valid_to"`
	PaymentType string        `json:"payment_type"`
	Status      string        `json:"status"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
	CreatedBy   sql.NullInt64 `json:"created_by"`
	UpdatedBy   sql.NullInt64 `json:"updated_by"`
	DeletedBy   sql.NullInt64 `json:"deleted_by"`
}

type Product struct {
	ID           int64         `json:"id"`
	CatID        int64         `json:"cat_id"`
	Name         string        `json:"name"`
	Amount       string        `json:"amount"`
	ProviderID   int64         `json:"provider_id"`
	ProviderCode string        `json:"provider_code"`
	Status       string        `json:"status"`
	Parent       int64         `json:"parent"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
	DeletedAt    sql.NullTime  `json:"deleted_at"`
	CreatedBy    sql.NullInt64 `json:"created_by"`
	UpdatedBy    sql.NullInt64 `json:"updated_by"`
	DeletedBy    sql.NullInt64 `json:"deleted_by"`
}

type Provider struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	User      string         `json:"user"`
	Secret    string         `json:"secret"`
	AddInfo1  string         `json:"add_info1"`
	AddInfo2  string         `json:"add_info2"`
	ValidFrom sql.NullTime   `json:"valid_from"`
	ValidTo   sql.NullTime   `json:"valid_to"`
	BaseUrl   sql.NullString `json:"base_url"`
	Method    sql.NullString `json:"method"`
	Inq       sql.NullString `json:"inq"`
	Pay       sql.NullString `json:"pay"`
	Adv       sql.NullString `json:"adv"`
	Cmt       sql.NullString `json:"cmt"`
	Rev       sql.NullString `json:"rev"`
	Status    string         `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	CreatedBy sql.NullInt64  `json:"created_by"`
	UpdatedBy sql.NullInt64  `json:"updated_by"`
	DeletedBy sql.NullInt64  `json:"deleted_by"`
}

type Role struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Level     int16         `json:"level"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	DeletedBy sql.NullInt64 `json:"deleted_by"`
}

type RoleUser struct {
	ID        int64         `json:"id"`
	RoleID    int64         `json:"role_id"`
	UserID    int64         `json:"user_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	DeletedBy sql.NullInt64 `json:"deleted_by"`
}

type Selling struct {
	ID         int64          `json:"id"`
	PartnerID  sql.NullInt64  `json:"partner_id"`
	CategoryID sql.NullInt64  `json:"category_id"`
	Amount     sql.NullString `json:"amount"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	CreatedBy  sql.NullInt64  `json:"created_by"`
	UpdatedBy  sql.NullInt64  `json:"updated_by"`
	DeletedBy  sql.NullInt64  `json:"deleted_by"`
}

type Transaction struct {
	ID           int64          `json:"id"`
	TxID         string         `json:"tx_id"`
	RefID        string         `json:"ref_id"`
	BillID       string         `json:"bill_id"`
	Sn           sql.NullString `json:"sn"`
	PaymentType  sql.NullString `json:"payment_type"`
	AddInfo1     sql.NullString `json:"add_info1"`
	AddInfo2     sql.NullString `json:"add_info2"`
	AddInfo3     sql.NullString `json:"add_info3"`
	CustName     sql.NullString `json:"cust_name"`
	Amount       sql.NullString `json:"amount"`
	Admin        sql.NullString `json:"admin"`
	TotAmount    sql.NullString `json:"tot_amount"`
	FeePartner   sql.NullString `json:"fee_partner"`
	FeePpob      sql.NullString `json:"fee_ppob"`
	FirstBalance sql.NullString `json:"first_balance"`
	LastBalance  sql.NullString `json:"last_balance"`
	ValidFrom    sql.NullTime   `json:"valid_from"`
	ValidTo      sql.NullTime   `json:"valid_to"`
	CatID        sql.NullInt64  `json:"cat_id"`
	CatName      sql.NullString `json:"cat_name"`
	ProdID       sql.NullInt64  `json:"prod_id"`
	ProdName     sql.NullString `json:"prod_name"`
	PartnerID    sql.NullInt64  `json:"partner_id"`
	PartnerName  sql.NullString `json:"partner_name"`
	ProviderID   sql.NullInt64  `json:"provider_id"`
	ProviderName sql.NullString `json:"provider_name"`
	Status       string         `json:"status"`
	ReqInqParams sql.NullString `json:"req_inq_params"`
	ResInqParams sql.NullString `json:"res_inq_params"`
	ReqPayParams sql.NullString `json:"req_pay_params"`
	ResPayParams sql.NullString `json:"res_pay_params"`
	ReqCmtParams sql.NullString `json:"req_cmt_params"`
	ResCmtParams sql.NullString `json:"res_cmt_params"`
	ReqAdvParams sql.NullString `json:"req_adv_params"`
	ResAdvParams sql.NullString `json:"res_adv_params"`
	ReqRevParams sql.NullString `json:"req_rev_params"`
	ResRevParams sql.NullString `json:"res_rev_params"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CreatedBy    sql.NullInt64  `json:"created_by"`
	UpdatedBy    sql.NullInt64  `json:"updated_by"`
	DeletedBy    sql.NullInt64  `json:"deleted_by"`
}

type User struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Username       string         `json:"username"`
	BankCode       sql.NullInt64  `json:"bank_code"`
	Password       sql.NullString `json:"password"`
	Balance        sql.NullString `json:"balance"`
	Phone          string         `json:"phone"`
	IdentityNumber string         `json:"identity_number"`
	VerifiedAt     sql.NullTime   `json:"verified_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedBy      sql.NullInt64  `json:"created_by"`
	UpdatedBy      sql.NullInt64  `json:"updated_by"`
	DeletedBy      sql.NullInt64  `json:"deleted_by"`
}
