// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO "transactions" (
    tx_id, "bill_id", cust_name, amount, "admin", tot_amount, fee_partner, fee_ppob, valid_from, valid_to,
    cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name,
    status, req_inq_params, res_inq_params, req_pay_params, res_pay_params,
    req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params,
    created_by, ref_id, created_at, first_balance, last_balance
) values (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
            $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, now(), $32, $33
         ) RETURNING id, tx_id, ref_id, bill_id, sn, add_info1, add_info2, add_info3, cust_name, amount, admin, tot_amount, fee_partner, fee_ppob, first_balance, last_balance, valid_from, valid_to, cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name, status, req_inq_params, res_inq_params, req_pay_params, res_pay_params, req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CreateTransactionParams struct {
	TxID         string         `json:"tx_id"`
	BillID       string         `json:"bill_id"`
	CustName     sql.NullString `json:"cust_name"`
	Amount       sql.NullString `json:"amount"`
	Admin        sql.NullString `json:"admin"`
	TotAmount    sql.NullString `json:"tot_amount"`
	FeePartner   sql.NullString `json:"fee_partner"`
	FeePpob      sql.NullString `json:"fee_ppob"`
	ValidFrom    sql.NullTime   `json:"valid_from"`
	ValidTo      sql.NullTime   `json:"valid_to"`
	CatID        sql.NullInt64  `json:"cat_id"`
	CatName      sql.NullString `json:"cat_name"`
	ProdID       sql.NullInt64  `json:"prod_id"`
	ProdName     sql.NullString `json:"prod_name"`
	PartnerID    sql.NullInt64  `json:"partner_id"`
	PartnerName  sql.NullString `json:"partner_name"`
	ProviderID   sql.NullInt64  `json:"provider_id"`
	ProviderName sql.NullString `json:"provider_name"`
	Status       string         `json:"status"`
	ReqInqParams sql.NullString `json:"req_inq_params"`
	ResInqParams sql.NullString `json:"res_inq_params"`
	ReqPayParams sql.NullString `json:"req_pay_params"`
	ResPayParams sql.NullString `json:"res_pay_params"`
	ReqCmtParams sql.NullString `json:"req_cmt_params"`
	ResCmtParams sql.NullString `json:"res_cmt_params"`
	ReqAdvParams sql.NullString `json:"req_adv_params"`
	ResAdvParams sql.NullString `json:"res_adv_params"`
	ReqRevParams sql.NullString `json:"req_rev_params"`
	ResRevParams sql.NullString `json:"res_rev_params"`
	CreatedBy    sql.NullInt64  `json:"created_by"`
	RefID        string         `json:"ref_id"`
	FirstBalance sql.NullString `json:"first_balance"`
	LastBalance  sql.NullString `json:"last_balance"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.TxID,
		arg.BillID,
		arg.CustName,
		arg.Amount,
		arg.Admin,
		arg.TotAmount,
		arg.FeePartner,
		arg.FeePpob,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CatID,
		arg.CatName,
		arg.ProdID,
		arg.ProdName,
		arg.PartnerID,
		arg.PartnerName,
		arg.ProviderID,
		arg.ProviderName,
		arg.Status,
		arg.ReqInqParams,
		arg.ResInqParams,
		arg.ReqPayParams,
		arg.ResPayParams,
		arg.ReqCmtParams,
		arg.ResCmtParams,
		arg.ReqAdvParams,
		arg.ResAdvParams,
		arg.ReqRevParams,
		arg.ResRevParams,
		arg.CreatedBy,
		arg.RefID,
		arg.FirstBalance,
		arg.LastBalance,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.RefID,
		&i.BillID,
		&i.Sn,
		&i.AddInfo1,
		&i.AddInfo2,
		&i.AddInfo3,
		&i.CustName,
		&i.Amount,
		&i.Admin,
		&i.TotAmount,
		&i.FeePartner,
		&i.FeePpob,
		&i.FirstBalance,
		&i.LastBalance,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CatID,
		&i.CatName,
		&i.ProdID,
		&i.ProdName,
		&i.PartnerID,
		&i.PartnerName,
		&i.ProviderID,
		&i.ProviderName,
		&i.Status,
		&i.ReqInqParams,
		&i.ResInqParams,
		&i.ReqPayParams,
		&i.ResPayParams,
		&i.ReqCmtParams,
		&i.ResCmtParams,
		&i.ReqAdvParams,
		&i.ResAdvParams,
		&i.ReqRevParams,
		&i.ResRevParams,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM "transactions"
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, tx_id, ref_id, bill_id, sn, add_info1, add_info2, add_info3, cust_name, amount, admin, tot_amount, fee_partner, fee_ppob, first_balance, last_balance, valid_from, valid_to, cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name, status, req_inq_params, res_inq_params, req_pay_params, res_pay_params, req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM "transactions"
WHERE id = $1 AND deleted_at is null LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.RefID,
		&i.BillID,
		&i.Sn,
		&i.AddInfo1,
		&i.AddInfo2,
		&i.AddInfo3,
		&i.CustName,
		&i.Amount,
		&i.Admin,
		&i.TotAmount,
		&i.FeePartner,
		&i.FeePpob,
		&i.FirstBalance,
		&i.LastBalance,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CatID,
		&i.CatName,
		&i.ProdID,
		&i.ProdName,
		&i.PartnerID,
		&i.PartnerName,
		&i.ProviderID,
		&i.ProviderName,
		&i.Status,
		&i.ReqInqParams,
		&i.ResInqParams,
		&i.ReqPayParams,
		&i.ResPayParams,
		&i.ReqCmtParams,
		&i.ResCmtParams,
		&i.ReqAdvParams,
		&i.ResAdvParams,
		&i.ReqRevParams,
		&i.ResRevParams,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getTransactionByRefID = `-- name: GetTransactionByRefID :one
SELECT id, tx_id, ref_id, bill_id, sn, add_info1, add_info2, add_info3, cust_name, amount, admin, tot_amount, fee_partner, fee_ppob, first_balance, last_balance, valid_from, valid_to, cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name, status, req_inq_params, res_inq_params, req_pay_params, res_pay_params, req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM "transactions"
WHERE ref_id = $1
AND status = '0'
AND partner_id = $2
AND to_char(created_at,'YYYY-MM-DD') = to_char(now(),'YYYY-MM-DD')
AND deleted_at is null
LIMIT 1
`

type GetTransactionByRefIDParams struct {
	RefID     string        `json:"ref_id"`
	PartnerID sql.NullInt64 `json:"partner_id"`
}

func (q *Queries) GetTransactionByRefID(ctx context.Context, arg GetTransactionByRefIDParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByRefID, arg.RefID, arg.PartnerID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.RefID,
		&i.BillID,
		&i.Sn,
		&i.AddInfo1,
		&i.AddInfo2,
		&i.AddInfo3,
		&i.CustName,
		&i.Amount,
		&i.Admin,
		&i.TotAmount,
		&i.FeePartner,
		&i.FeePpob,
		&i.FirstBalance,
		&i.LastBalance,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CatID,
		&i.CatName,
		&i.ProdID,
		&i.ProdName,
		&i.PartnerID,
		&i.PartnerName,
		&i.ProviderID,
		&i.ProviderName,
		&i.Status,
		&i.ReqInqParams,
		&i.ResInqParams,
		&i.ReqPayParams,
		&i.ResPayParams,
		&i.ReqCmtParams,
		&i.ResCmtParams,
		&i.ReqAdvParams,
		&i.ResAdvParams,
		&i.ReqRevParams,
		&i.ResRevParams,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getTransactionByTxID = `-- name: GetTransactionByTxID :one
SELECT id, tx_id, ref_id, bill_id, sn, add_info1, add_info2, add_info3, cust_name, amount, admin, tot_amount, fee_partner, fee_ppob, first_balance, last_balance, valid_from, valid_to, cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name, status, req_inq_params, res_inq_params, req_pay_params, res_pay_params, req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM "transactions"
WHERE tx_id = $1 AND deleted_at is null LIMIT 1
`

func (q *Queries) GetTransactionByTxID(ctx context.Context, txID string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByTxID, txID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.RefID,
		&i.BillID,
		&i.Sn,
		&i.AddInfo1,
		&i.AddInfo2,
		&i.AddInfo3,
		&i.CustName,
		&i.Amount,
		&i.Admin,
		&i.TotAmount,
		&i.FeePartner,
		&i.FeePpob,
		&i.FirstBalance,
		&i.LastBalance,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CatID,
		&i.CatName,
		&i.ProdID,
		&i.ProdName,
		&i.PartnerID,
		&i.PartnerName,
		&i.ProviderID,
		&i.ProviderName,
		&i.Status,
		&i.ReqInqParams,
		&i.ResInqParams,
		&i.ReqPayParams,
		&i.ResPayParams,
		&i.ReqCmtParams,
		&i.ResCmtParams,
		&i.ReqAdvParams,
		&i.ResAdvParams,
		&i.ReqRevParams,
		&i.ResRevParams,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getTransactionPending = `-- name: GetTransactionPending :one
SELECT id, tx_id, ref_id, bill_id, sn, add_info1, add_info2, add_info3, cust_name, amount, admin, tot_amount, fee_partner, fee_ppob, first_balance, last_balance, valid_from, valid_to, cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name, status, req_inq_params, res_inq_params, req_pay_params, res_pay_params, req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM "transactions"
WHERE bill_id = $1
  AND status = '4'
  AND to_char(created_at,'YYYY-MM-DD') = to_char(now(),'YYYY-MM-DD')
  AND deleted_at is null
    LIMIT 1
`

func (q *Queries) GetTransactionPending(ctx context.Context, billID string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionPending, billID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.RefID,
		&i.BillID,
		&i.Sn,
		&i.AddInfo1,
		&i.AddInfo2,
		&i.AddInfo3,
		&i.CustName,
		&i.Amount,
		&i.Admin,
		&i.TotAmount,
		&i.FeePartner,
		&i.FeePpob,
		&i.FirstBalance,
		&i.LastBalance,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CatID,
		&i.CatName,
		&i.ProdID,
		&i.ProdName,
		&i.PartnerID,
		&i.PartnerName,
		&i.ProviderID,
		&i.ProviderName,
		&i.Status,
		&i.ReqInqParams,
		&i.ResInqParams,
		&i.ReqPayParams,
		&i.ResPayParams,
		&i.ReqCmtParams,
		&i.ResCmtParams,
		&i.ReqAdvParams,
		&i.ResAdvParams,
		&i.ReqRevParams,
		&i.ResRevParams,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listTransaction = `-- name: ListTransaction :many
SELECT id, tx_id, ref_id, bill_id, sn, add_info1, add_info2, add_info3, cust_name, amount, admin, tot_amount, fee_partner, fee_ppob, first_balance, last_balance, valid_from, valid_to, cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name, status, req_inq_params, res_inq_params, req_pay_params, res_pay_params, req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM "transactions"
WHERE deleted_at is null
AND DATE(created_at) >= to_date($3,'YYYY-MM-DD')
AND DATE(created_at) <= to_date($4,'YYYY-MM-DD')
AND (CASE WHEN $5::bool THEN status = $6 ELSE TRUE END)
AND (CASE WHEN $7::bool THEN cat_id = $8 ELSE TRUE END)
AND (CASE WHEN $9::bool THEN partner_id = $10 ELSE TRUE END)
AND (CASE WHEN $11::bool THEN created_by = $12 ELSE TRUE END)
ORDER BY created_at
LIMIT $1
OFFSET $2
`

type ListTransactionParams struct {
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
	FromDate  string        `json:"from_date"`
	ToDate    string        `json:"to_date"`
	IsStatus  bool          `json:"is_status"`
	Status    string        `json:"status"`
	IsCat     bool          `json:"is_cat"`
	CatID     sql.NullInt64 `json:"cat_id"`
	IsPartner bool          `json:"is_partner"`
	PartnerID sql.NullInt64 `json:"partner_id"`
	IsCreated bool          `json:"is_created"`
	CreatedBy sql.NullInt64 `json:"created_by"`
}

func (q *Queries) ListTransaction(ctx context.Context, arg ListTransactionParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransaction,
		arg.Limit,
		arg.Offset,
		arg.FromDate,
		arg.ToDate,
		arg.IsStatus,
		arg.Status,
		arg.IsCat,
		arg.CatID,
		arg.IsPartner,
		arg.PartnerID,
		arg.IsCreated,
		arg.CreatedBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.RefID,
			&i.BillID,
			&i.Sn,
			&i.AddInfo1,
			&i.AddInfo2,
			&i.AddInfo3,
			&i.CustName,
			&i.Amount,
			&i.Admin,
			&i.TotAmount,
			&i.FeePartner,
			&i.FeePpob,
			&i.FirstBalance,
			&i.LastBalance,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CatID,
			&i.CatName,
			&i.ProdID,
			&i.ProdName,
			&i.PartnerID,
			&i.PartnerName,
			&i.ProviderID,
			&i.ProviderName,
			&i.Status,
			&i.ReqInqParams,
			&i.ResInqParams,
			&i.ReqPayParams,
			&i.ResPayParams,
			&i.ReqCmtParams,
			&i.ResCmtParams,
			&i.ReqAdvParams,
			&i.ResAdvParams,
			&i.ReqRevParams,
			&i.ResRevParams,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInactiveTransaction = `-- name: UpdateInactiveTransaction :one
UPDATE "transactions" SET deleted_by = $2, deleted_at = now() WHERE id = $1
RETURNING id, tx_id, ref_id, bill_id, sn, add_info1, add_info2, add_info3, cust_name, amount, admin, tot_amount, fee_partner, fee_ppob, first_balance, last_balance, valid_from, valid_to, cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name, status, req_inq_params, res_inq_params, req_pay_params, res_pay_params, req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type UpdateInactiveTransactionParams struct {
	ID        int64         `json:"id"`
	DeletedBy sql.NullInt64 `json:"deleted_by"`
}

func (q *Queries) UpdateInactiveTransaction(ctx context.Context, arg UpdateInactiveTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateInactiveTransaction, arg.ID, arg.DeletedBy)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.RefID,
		&i.BillID,
		&i.Sn,
		&i.AddInfo1,
		&i.AddInfo2,
		&i.AddInfo3,
		&i.CustName,
		&i.Amount,
		&i.Admin,
		&i.TotAmount,
		&i.FeePartner,
		&i.FeePpob,
		&i.FirstBalance,
		&i.LastBalance,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CatID,
		&i.CatName,
		&i.ProdID,
		&i.ProdName,
		&i.PartnerID,
		&i.PartnerName,
		&i.ProviderID,
		&i.ProviderName,
		&i.Status,
		&i.ReqInqParams,
		&i.ResInqParams,
		&i.ReqPayParams,
		&i.ResPayParams,
		&i.ReqCmtParams,
		&i.ResCmtParams,
		&i.ReqAdvParams,
		&i.ResAdvParams,
		&i.ReqRevParams,
		&i.ResRevParams,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE "transactions"
SET
    "status" = CASE
            WHEN $1::bool
                THEN $2
            ELSE status
            END,
    "first_balance" = CASE
                   WHEN $3::bool
                THEN $4
                   ELSE first_balance
        END,
    "last_balance" = CASE
                   WHEN $5::bool
                THEN $6
                   ELSE last_balance
        END,
    res_inq_params = CASE
               WHEN $7::bool
                THEN $8
               ELSE res_inq_params
        END,
    req_pay_params = CASE
                 WHEN $9::bool
                    THEN $10
                 ELSE req_pay_params
        END,
    res_pay_params = CASE
                 WHEN $11::bool
                    THEN $12
                 ELSE res_pay_params
        END,
    req_cmt_params = CASE
                    WHEN $13::bool
                    THEN $14
                    ELSE req_cmt_params
        END,
    res_cmt_params = CASE
                    WHEN $15::bool
                    THEN $16
                    ELSE res_cmt_params
        END,
    req_adv_params = CASE
                     WHEN $17::bool
                    THEN $18
                     ELSE req_adv_params
        END,
    res_adv_params = CASE
                   WHEN $19::bool
                    THEN $20
                   ELSE res_adv_params
        END,
    req_rev_params = CASE
                   WHEN $21::bool
                    THEN $22
                   ELSE req_rev_params
        END,
    sn = CASE
            WHEN $23::bool
                THEN $24
            ELSE sn
        END,
    add_info1 = CASE
                         WHEN $25::bool
                    THEN $26
                         ELSE add_info1
        END,
    add_info2 = CASE
                         WHEN $27::bool
                    THEN $28
                         ELSE add_info2
        END,
    add_info3 = CASE
                         WHEN $29::bool
                    THEN $30
                         ELSE add_info3
        END,
    updated_by = $31,
    updated_at = now()
WHERE
    id = $32
RETURNING id, tx_id, ref_id, bill_id, sn, add_info1, add_info2, add_info3, cust_name, amount, admin, tot_amount, fee_partner, fee_ppob, first_balance, last_balance, valid_from, valid_to, cat_id, cat_name, prod_id, prod_name, partner_id, partner_name, provider_id, provider_name, status, req_inq_params, res_inq_params, req_pay_params, res_pay_params, req_cmt_params, res_cmt_params, req_adv_params, res_adv_params, req_rev_params, res_rev_params, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type UpdateTransactionParams struct {
	SetStatus       bool           `json:"set_status"`
	Status          string         `json:"status"`
	SetFirstBalance bool           `json:"set_first_balance"`
	FirstBalance    sql.NullString `json:"first_balance"`
	SetLastBalance  bool           `json:"set_last_balance"`
	LastBalance     sql.NullString `json:"last_balance"`
	SetResInqParams bool           `json:"set_res_inq_params"`
	ResInqParams    sql.NullString `json:"res_inq_params"`
	SetReqPayParams bool           `json:"set_req_pay_params"`
	ReqPayParams    sql.NullString `json:"req_pay_params"`
	SetResPayParams bool           `json:"set_res_pay_params"`
	ResPayParams    sql.NullString `json:"res_pay_params"`
	SetReqCmtParams bool           `json:"set_req_cmt_params"`
	ReqCmtParams    sql.NullString `json:"req_cmt_params"`
	SetResCmtParams bool           `json:"set_res_cmt_params"`
	ResCmtParams    sql.NullString `json:"res_cmt_params"`
	SetReqAdvParams bool           `json:"set_req_adv_params"`
	ReqAdvParams    sql.NullString `json:"req_adv_params"`
	SetResAdvParams bool           `json:"set_res_adv_params"`
	ResAdvParams    sql.NullString `json:"res_adv_params"`
	SetReqRevParams bool           `json:"set_req_rev_params"`
	ReqRevParams    sql.NullString `json:"req_rev_params"`
	SetSn           bool           `json:"set_sn"`
	Sn              sql.NullString `json:"sn"`
	SetInfo1        bool           `json:"set_info1"`
	AddInfo1        sql.NullString `json:"add_info1"`
	SetInfo2        bool           `json:"set_info2"`
	AddInfo2        sql.NullString `json:"add_info2"`
	SetInfo3        bool           `json:"set_info3"`
	AddInfo3        sql.NullString `json:"add_info3"`
	UpdatedBy       sql.NullInt64  `json:"updated_by"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.SetStatus,
		arg.Status,
		arg.SetFirstBalance,
		arg.FirstBalance,
		arg.SetLastBalance,
		arg.LastBalance,
		arg.SetResInqParams,
		arg.ResInqParams,
		arg.SetReqPayParams,
		arg.ReqPayParams,
		arg.SetResPayParams,
		arg.ResPayParams,
		arg.SetReqCmtParams,
		arg.ReqCmtParams,
		arg.SetResCmtParams,
		arg.ResCmtParams,
		arg.SetReqAdvParams,
		arg.ReqAdvParams,
		arg.SetResAdvParams,
		arg.ResAdvParams,
		arg.SetReqRevParams,
		arg.ReqRevParams,
		arg.SetSn,
		arg.Sn,
		arg.SetInfo1,
		arg.AddInfo1,
		arg.SetInfo2,
		arg.AddInfo2,
		arg.SetInfo3,
		arg.AddInfo3,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.RefID,
		&i.BillID,
		&i.Sn,
		&i.AddInfo1,
		&i.AddInfo2,
		&i.AddInfo3,
		&i.CustName,
		&i.Amount,
		&i.Admin,
		&i.TotAmount,
		&i.FeePartner,
		&i.FeePpob,
		&i.FirstBalance,
		&i.LastBalance,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CatID,
		&i.CatName,
		&i.ProdID,
		&i.ProdName,
		&i.PartnerID,
		&i.PartnerName,
		&i.ProviderID,
		&i.ProviderName,
		&i.Status,
		&i.ReqInqParams,
		&i.ResInqParams,
		&i.ReqPayParams,
		&i.ResPayParams,
		&i.ReqCmtParams,
		&i.ResCmtParams,
		&i.ReqAdvParams,
		&i.ResAdvParams,
		&i.ReqRevParams,
		&i.ResRevParams,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}
